FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

RUN mkdir -p .tanstack src node_modules && chown -R node:node /app
USER node

COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/home/node/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

COPY --chown=node:node . .

EXPOSE 5173

CMD ["pnpm", "run", "dev"]
